# Generated by Django 5.1.1 on 2024-09-16 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('rood_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goal', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField()),
                ('image', models.CharField(max_length=150)),
                ('pos', models.IntegerField()),
                ('is_end', models.BooleanField()),
                ('invitation_num', models.IntegerField()),
                ('user_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
